// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHK9ULEV8d4ln8f7DMtCAJyhOik12iXE',
    appId: '1:112710046445:web:c5f82a86ddebf1a28c32e4',
    messagingSenderId: '112710046445',
    projectId: 'capstone-11bce',
    authDomain: 'capstone-11bce.firebaseapp.com',
    databaseURL: 'https://capstone-11bce-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-11bce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoIOz6Wde5iRAOlAwYteJsm7FC6sZUUlM',
    appId: '1:112710046445:android:95fac085ac7bd5c08c32e4',
    messagingSenderId: '112710046445',
    projectId: 'capstone-11bce',
    databaseURL: 'https://capstone-11bce-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-11bce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApHm4ndsbi5qm662NxYBU52lBakW5ozpU',
    appId: '1:112710046445:ios:c94eefd5aa32dffc8c32e4',
    messagingSenderId: '112710046445',
    projectId: 'capstone-11bce',
    databaseURL: 'https://capstone-11bce-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-11bce.firebasestorage.app',
    iosBundleId: 'com.example.capstoneHealthcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApHm4ndsbi5qm662NxYBU52lBakW5ozpU',
    appId: '1:112710046445:ios:c94eefd5aa32dffc8c32e4',
    messagingSenderId: '112710046445',
    projectId: 'capstone-11bce',
    databaseURL: 'https://capstone-11bce-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-11bce.firebasestorage.app',
    iosBundleId: 'com.example.capstoneHealthcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxHK9ULEV8d4ln8f7DMtCAJyhOik12iXE',
    appId: '1:112710046445:web:8ce859e8b165f4d08c32e4',
    messagingSenderId: '112710046445',
    projectId: 'capstone-11bce',
    authDomain: 'capstone-11bce.firebaseapp.com',
    databaseURL: 'https://capstone-11bce-default-rtdb.firebaseio.com',
    storageBucket: 'capstone-11bce.firebasestorage.app',
  );
}
